### ISSUE TITLE
Formatting not properly encoded

### ISSUE THREAD

**Issue by briandennis** [molnarmark/carbonSublime#1]
## Expected Behavior 
Formatting would match that of Sublime.

![image](https://user-images.githubusercontent.com/10078572/35983159-1663eb88-0cb7-11e8-90fd-1e3f443babb3.png)

## Actual Behavior
Spacing was off, looks like newlines are not being properly encoded. 

![image](https://user-images.githubusercontent.com/10078572/35983382-845fd714-0cb7-11e8-951f-198c923e3682.png)

**Comment by molnarmark** [comment]
That's curious. I've typed in the example you provided and this is what I got:
![](https://image.prntscr.com/image/3dsLS6HvTlSNiFDC7Vcbhw.png?raw=true)

I've tried with both spaces and tabs, and there seem to be no issue on my end. Interesting.

**Comment by briandennis** [comment]
I think the problem is [here](https://github.com/molnarmark/carbonSublime/blob/master/carbonSublime.py#L15). Newlines are encoded differently depending on the platform and on Unix-like systems `\n` and `\t` should not be replaced.

I don't know much about Sublime plugins, but maybe adding a conditional check based on the platform  and only replacing them if on Windows would work?

**Comment by molnarmark** [comment]
Could you try [this](https://github.com/molnarmark/carbonSublime/commit/49ade3b94644fef5a8a500b95c3a60921adf5b5f) commit? I'm working in my Windows environment and can't quickly switch over to my linux instance.

**Comment by briandennis** [comment]
Yep, that fixed it! 🎉 Thanks so much!

**Comment by molnarmark** [comment]
You're welcome. 👍 I also just fixed a redundancy issue, seems like I missed it before. :smile:
