### ISSUE TITLE
Cannot open:Preferences > Package Settings > carbonSublime > Settings

### ISSUE THREAD

**Issue by LousenJay** [molnarmark/carbonSublime#19]
**Describe the problem**
When I open 'Preferences > Package Settings > carbonSublime > Settings' it  display error and unable to open.

**Picture**
![sublimeText-bugs](https://www.lousenjay.top/images/show/others/sublimeText-bugs.png)

**Sublime Text 3 version**
Version 3.1.1,Build 3176

**Comment by rizkysyazuli** [comment]
Aye.. same here..

<img width="532" alt="tangkapan layar 2019-01-17 21 46 57" src="https://user-images.githubusercontent.com/152221/51326333-7bc3d800-1aa1-11e9-84cb-4128f911a86d.png">

**Comment by brichards** [comment]
Ditto. Looks like the file isn't being created on installation.

Creating the file manually works and allows me to override details.

Hope this helps!

**Comment by molnarmark** [comment]
Thanks for the report. I'm kinda busy lately, so if any of you want to submit a PR, its welcome! If not, I'll eventually get around to fix it. Interesting that it happens though.

**Comment by gh640** [comment]
Thank you for sharing the issue. I could reproduce the error.

@molnarmark I'm sorry, this was caused since I didn't use the proper package name `Carbon` in `Main.sublime-menu`. I made a PR to fix this.
