### ISSUE TITLE
Several issues with text detection and alignment

### ISSUE THREAD

**Issue by maelrawn** [molnarmark/carbonSublime#2]
1. The plugin does not detect newlines of any sort, and will output everything it finds on the same line. [This is 12 lines of input.](https://carbon.now.sh/?bg=rgba(38,139,210,100)&t=solarized%20dark&l=auto&ds=true&wc=true&wa=true&pv=48px&ph=32px&ln=true&code=then%20newbrightness="$1"fiif%20((%20$newbrightness%20<=%200))%20||%20((%20$newbrightness%20>%20100%20));thenecho%20"Proper%20usage%20is%20'brightness%20<num>',%20where%20num%20is%20between%201%20and%20100."exitfiif%20[%20"$newbrightness"%20-ne%201%20]thennewbrightness=$(($newbrightness%20*%2075))fiecho%20$newbrightness%20|%20sudo%20tee%20/sys/class/backlight/intel_backlight/brightness)
2. It also stops collecting text at any `#` character. This will wind up giving you the default template when trying to export a whole shell script, as it stops at the opening `#!`. [Example here.](https://carbon.now.sh/?bg=rgba(38,139,210,100)&t=solarized%20dark&l=auto&ds=true&wc=true&wa=true&pv=48px&ph=32px&ln=true&code=maxbrightness=100newbrightness=1if%20[%20"$)

Excerpts taken from [this script](https://bitbucket.org/maelrawn/dotfiles-1-solar-ezzed/src/c119629cde97c1fbeb46b32b5afc776aec275513/brightness?at=master&fileviewer=file-view-default), I hope they help.

**Comment by maelrawn** [comment]
Update: I am on Arch Linux x86_64, so I removed line #17 `if sys.platform == "win32":`, which solved the no-newlines problem. However, I'm at a loss for the `#` problem.

**Comment by molnarmark** [comment]
The first issue was mentioned and resolved at [#1](1).
What system are you running?

**Comment by molnarmark** [comment]
I'm gonna go on my linux instance sometime tomorrow and test out the plugin there. However, [#1](1) apparently fixed the no newlines issue.

**Comment by molnarmark** [comment]
If you manage to figure it out before me, a PR is welcome. 👍

**Comment by maelrawn** [comment]
Apparently trying to load carbon.now.sh with any `#` in the URL causes it to drop the `#` and everything after it. Interestingly, when inserting `#`'s into the text from an already-loaded page, it inserts them into the URL itself, but fails with the same issue if you visit that same URL it created. 

I'm not familiar with html or anything, so I can't move forwards with it (if it even is something that can be done outside of the carbon team). I'll put up the issue with them, if it doesn't exist already.

**Comment by maelrawn** [comment]
Opened an issue with carbon [here](https://github.com/dawnlabs/carbon/issues/229), as the issue appears to be independent of carbonSublime.

**Comment by molnarmark** [comment]
Thank you. I'm gonna close this for now, i'll follow through the issue you opened.
