### ISSUE TITLE
"width" setting doesn't change the default width (680px) upon sharing.

### ISSUE THREAD

**Issue by a-y-u-s-h** [molnarmark/carbonSublime#23]

**Comment by molnarmark** [comment]
Hi. I'm kind of busy at the moment, would you like to send in a PR for this fix? I'd appreciate it :) Otherwise, I'll get to it soon.

**Comment by molnarmark** [comment]
Upon checking it further, it looks like setting the width doesn't have a query parameter for it.

All we have is `widthAdjustment`, which is a boolean, and `exportSize`, which can be values like 2x, 4x.

Let me know if I overlooked something though.

**Comment by a-y-u-s-h** [comment]
Yup, it seems there's no query parameter for width :(

**Comment by molnarmark** [comment]
Yeah. I'd suggest opening an issue in the Carbon repository, I've contributed to the project in the past, they are kind people. :)

If they add it, I'll be sure to add it as well.
