### ISSUE TITLE
Add to Package Control

### ISSUE THREAD

**Issue by royduin** [molnarmark/carbonSublime#4]
As suggested in the readme, it would be nice if it's listed. Info: https://packagecontrol.io/docs/submitting_a_package

**Comment by royduin** [comment]
There is already a PR, see: https://github.com/wbond/package_control_channel/pull/6920 but that one is for this implementation: https://github.com/stianmartinsen/sublime-carbon-now-sh

**Comment by molnarmark** [comment]
In progress. 😃

**Comment by royduin** [comment]
Nice! For reference: https://github.com/wbond/package_control_channel/pull/6947, let's wait 😎
