### ISSUE TITLE
fail send code to formating

### ISSUE THREAD

**Issue by al3x609** [molnarmark/carbonSublime#5]
when, i send (f3) my code, in the browser only show the settings but no my code, it show the default test code, help me. 
![testcarbon](https://user-images.githubusercontent.com/4086644/36553753-30de9eee-17cb-11e8-86ea-3d28e91de5e8.png)

my settings  file
{
	"background-color": "rgba(84,146,187,1)",
	"color-scheme": "material",
	"drop-shadow": "true",
	"line-numbers": "true",
	"window-controls": "true"
}

**Comment by molnarmark** [comment]
I'd need the test code.

**Comment by al3x609** [comment]
of course
https://gist.github.com/al3x609/8e8653086f35366d0c6620cb4e13b935

**Comment by molnarmark** [comment]
The issue isn't related to carbonSublime. Carbon itself only supports up to 500 characters (for some reason).
