### ISSUE TITLE
Any plan for a new release?

### ISSUE THREAD

**Issue by gh640** [molnarmark/carbonSublime#9]
I'm interested in the command introduced after the last release. Do you have any plan for a new release? How can I help for that? Thank you in advance.

**Comment by molnarmark** [comment]
Which command are you talking about that?

**Comment by gh640** [comment]
Thank you for your reply.

I'm sorry, my explanation was vague. I was talking about the command in Command Palette labeled `Carbon: share selection` and introduced in the following commit.

https://github.com/molnarmark/carbonSublime/commit/05b6773eb73037293cec4b70ddcfbe0cd32c4329 

However, I've now noticed that the command `carbon_sublime` doesn't work in the dev HEAD. 

<img width="1218" alt="20180713-2" src="https://user-images.githubusercontent.com/3532528/42698652-7ed4d8b4-86f9-11e8-8af2-02c3f573aca8.png">

```text
>>> view.run_command('carbon_sublime')
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/.../Sublime Text 3/Packages/carbonSublime/carbonSublime.py", line 96, in run
    code = self.normalize_code()
  File "/.../Sublime Text 3/Packages/carbonSublime/carbonSublime.py", line 107, in normalize_code
    whitespace = convert_tabs_using_tab_size(view, get_whitespace_from_line_begin(view, view.sel()[0]))
NameError: global name 'get_whitespace_from_line_begin' is not defined
```

So at least we need to solve this problem before making a new release, maybe. Is my understanding correct?

**Comment by gh640** [comment]
I filed a new issue #10 for the `NameError` mentioned in the previous comment since it's a different topic.

**Comment by molnarmark** [comment]
I currently don't have time for any of my open source projects, feel free to send in a PR though.

**Comment by gh640** [comment]
I see. I got it. Thank you very much for taking time in such a situation :) I'll try.

**Comment by gh640** [comment]
It looks like making a new release needs a new tag and I cannot make a tag in PR... So we have several options here, I think.

- a) Give up to make a new release until you have a time.
- b) Add me as a temporary collaborator of this repo.

I don't push you. Please consider it. Thanks :)

(Edited) FYI, I have a plan to improve in the following points:

- Make a new release(s).
- Make the code follows pep8.
- Make the indent space strip function switchable.
- Add a status message when the long `body` is trimmed (to `3400`).
- Add tests.
- Add description for usage in README.

**Comment by molnarmark** [comment]
I've added you as a contributor. You are free to do whatever you want to improve the project. Thanks for your help. :)

**Comment by gh640** [comment]
It's very generous of you to allow me. If you find anything improper I do here, please let me know (and don't hesitate to revert the changes). Thanks!
